In [3]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.0-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sahithi.s\appdata\roaming\python\python313\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sahithi.s\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\sahithi.s\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.0-cp313-cp313-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ------- -------------------------------- 1.8/9.7 MB 11.3 MB/s eta 0:00:01
   ------------------ --------------------- 4.5/9.7 MB 14.9 MB/s eta 0:00:01
   ---------------------------- ----------- 6.8/9.7 MB 11.9 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 12.3 MB/s eta 0:00:00
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas
Successfully installed pandas-3.0.0 tzdata-2025.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd
mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

In [6]:
a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

0    1
1    7
2    2
dtype: int64

In [7]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)

   calories  duration
0       420        50
1       380        40
2       390        45

In [8]:
print(df.loc[0])

calories    420
duration     50
Name: 0, dtype: int64

In [12]:
#difference between loc and iloc 
print(df.iloc[0])

calories    420
duration     50
Name: 0, dtype: int64

In [13]:
data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

In [14]:
print(df.head())

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406

In [15]:
print(df.tail())

   Duration  Pulse  Maxpulse  Calories
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

In [16]:
columns=['name','age','gender','job']
user1=pd.DataFrame([['sahithi',20,'F','student'],
                    ['ramu',21,'M','student']],columns=columns)

In [17]:
user2=pd.DataFrame([['Pathi',20,'M','student'],
                    ['Durga',21,'F','student']],columns=columns)
user3=pd.DataFrame([['Kishore',20,'M','scientist'],
                    ['krishna',21,'M','manager']],columns=columns)

In [18]:
user4=pd.DataFrame(dict(name=['Nani','Depithi'],
                        age=[33,44],gender=['M','F'],
                        job=['engineer','scientist']))
print(user4)

      name  age gender        job
0     Nani   33      M   engineer
1  Depithi   44      F  scientist

In [19]:
user5=pd.DataFrame(dict(name=['sahithi','Pathi','Durga', 'Krishna','Nani','Depithi'],
                        height=[165,180,171,160,184,165]))
print(user5)

      name  height
0  sahithi     165
1    Pathi     180
2    Durga     171
3  Krishna     160
4     Nani     184
5  Depithi     165

In [22]:
users=pd.concat([user1,user2,user3,user4])
users

      name  age gender        job
0  sahithi   20      F    student
1     ramu   21      M    student
0    Pathi   20      M    student
1    Durga   21      F    student
0  Kishore   20      M  scientist
1  krishna   21      M    manager
0     Nani   33      M   engineer
1  Depithi   44      F  scientist

In [23]:
users=pd.merge(users,user5,on='name',how='outer')
print(users)

      name   age gender        job  height
0  Depithi  44.0      F  scientist   165.0
1    Durga  21.0      F    student   171.0
2  Kishore  20.0      M  scientist     NaN
3  Krishna   NaN    NaN        NaN   160.0
4     Nani  33.0      M   engineer   184.0
5    Pathi  20.0      M    student   180.0
6  krishna  21.0      M    manager     NaN
7     ramu  21.0      M    student     NaN
8  sahithi  20.0      F    student   165.0

In [24]:
'''Consider a DataFrame with columns like Name, Math, and Science. Using melt(),
 you can transform it so that Name remains an identifier, and Math and Science
  are unpivoted into a new Subject column and a Score column.

  Pivot-->Rows to columns when convert the rows into columns one column into multiple cloumns.we used Present information in a new perspective form
  UnPivot -->Collumns to rows eaiser to anlaysis of the dataframe .we used in the easier to perform on a row-by-row basis
'''

data = {'Name': ['Alice', 'Bob'],
        'Math': [90, 85],
        'Science': [88, 92]}
df = pd.DataFrame(data)
print(df)
# Melt the DataFrame
melted_df = pd.melt(df, id_vars=['Name'], var_name='Subject', value_name='Score')

print('melted df',melted_df)

    Name  Math  Science
0  Alice    90       88
1    Bob    85       92
melted df     Name  Subject  Score
0  Alice     Math     90
1    Bob     Math     85
2  Alice  Science     88
3    Bob  Science     92

In [25]:
'''Use pandas.pivot() when your data strictly adheres to a one-to-one mapping
between the index and columns values, and you don't need to perform any aggregation.'''
#Need to aggregate data
print(melted_df.pivot(index='Name',columns='Subject',values='Score'))

Subject  Math  Science
Name
Alice      90       88
Bob        85       92

In [26]:
type(df)

pandas.DataFrame

In [28]:
df.describe()

            Math    Science
count   2.000000   2.000000
mean   87.500000  90.000000
std     3.535534   2.828427
min    85.000000  88.000000
25%    86.250000  89.000000
50%    87.500000  90.000000
75%    88.750000  91.000000
max    90.000000  92.000000

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     2 non-null      str
 1   Math     2 non-null      int64
 2   Science  2 non-null      int64
dtypes: int64(2), str(1)
memory usage: 180.0 bytes

In [30]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: str

In [31]:
df[['Name','Math']]

    Name  Math
0  Alice    90
1    Bob    85

In [32]:
df.sort_values(by='Math')

    Name  Math  Science
1    Bob    85       92
0  Alice    90       88

In [34]:
df.isnull()

    Name   Math  Science
0  False  False    False
1  False  False    False

In [35]:
df.isnull().sum()

Name       0
Math       0
Science    0
dtype: int64

In [36]:
df.duplicated()

0    False
1    False
dtype: bool